name = "ACAFact"
uuid = "2e0d8c30-fd72-45bd-a04c-a052d00f6fe4"
authors = ["Chris Geoga <geoga@wisc.edu>"]
version = "0.2.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
